trigger:
- main

pool:
  vmImage: 'windows-latest'

jobs:
- job: Build
  displayName: 'Build Job'
  steps:
  - checkout: self

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '3.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        # Your PowerShell script for building goes here

- job: Test
  displayName: 'Test Job'
  dependsOn: Build
  steps:
  - checkout: self

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '3.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        # Your PowerShell script for testing goes here

- job: Deploy
  displayName: 'Deploy Job'
  dependsOn: Test
  steps:
  - checkout: self

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '3.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        # Your PowerShell script for deployment goes here
